# Generated by Django 2.1.15 on 2021-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('cod_product', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
